FROM openjdk:11.0.2-jre-slim
EXPOSE 8989
ADD target/microservice-demo-turbine-server-0.0.1-SNAPSHOT.jar microservice-demo-turbine-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","microservice-demo-turbine-server-0.0.1-SNAPSHOT.jar"]
