FROM openjdk:11.0.2-jre-slim
EXPOSE 8761
ADD target/microservice-demo-eureka-server-0.0.1-SNAPSHOT.jar microservice-demo-eureka-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","microservice-demo-eureka-server-0.0.1-SNAPSHOT.jar"]

