FROM openjdk:11.0.2-jre-slim
EXPOSE 8080
ADD target/microservice-demo-catalog-0.0.1-SNAPSHOT.jar microservice-demo-catalog-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","microservice-demo-catalog-0.0.1-SNAPSHOT.jar"]

